### ISSUE TITLE
Uninstall - iframe persists

### ISSUE THREAD

**Issue by chrismllr** [sweettooth/ember-cli-stripe#10]
I've done a ```npm rm --save-dev ember-cli-stripe``` and the iframe (pointing to js.stripe.com/v2/channel.html etc etc) is still on my body tag when I inspect in dev tools. Was this an error in my npm rm or do I have to do something else to get rid of the iframe

**Comment by wcurtis** [comment]
Strange. Try this to make sure there's no weird dependency caching. Also confirm that there's no `ember-cli-stripe` entry in your `package.json`

```
# Remove temp dev folders
rm -rf node_modules bower_components dist tmp

# Grab all fresh dependencies
npm install && bower install
```

**Comment by chrismllr** [comment]
Hey @wcurtis,

I believe this may be an error on my part. I am using another Stripe add-on, and I mistakenly thought that the iframe was a ghost of the stripe modal that this add-on uses.... But I guess the iframe is if you have any instance of stripe in your app? Seems strange, but Ive realized this likely isn't ember-cli-stripe specific.. Thanks for your response!

**Comment by wcurtis** [comment]
No worries! Will close the issue.
