### ISSUE TITLE
Depreciation - Ember 1.13

### ISSUE THREAD

**Issue by mnowik** [sweettooth/ember-cli-stripe#12]
Depreciation appears when using ember-cli-stripe with Ember 1.13.
`{{# if hasBlock }}`

**Comment by wcurtis** [comment]
Thanks for reporting this. Looks like adding `hasBlock` instead of `template` is needed.
http://emberjs.com/blog/2015/06/12/ember-1-13-0-released.html#toc_component-block-info

> Ember.js 1.13 introduces two new template keywords that provide reflection on how a component is called.
> hasBlock will be true when a component is invoked in block form. For example given this component:
```handlebars
{{! app/components/show-full-name.hbs }}
{{#if hasBlock}}
  {{yield fullName}}
{{else}}
  {{fullName}}
{{/if}}
```
