### ISSUE TITLE
How can i override stripe-checkout.hbs?

### ISSUE THREAD

**Issue by rromanchuk** [sweettooth/ember-cli-stripe#14]
Or what's the best practice for injecting dom into the component (i need more than just a label)

**Comment by rromanchuk** [comment]
NVM, don't have to, you can simply pass a block, super simple. Great design.

**Comment by wcurtis** [comment]
:+1:

**Comment by lcpriest** [comment]
If I understand correctly, there is no default form template or styling? It is all custom-built?

**Comment by wcurtis** [comment]
The only thing you'll need to style is the button itself. The rest of the Stripe checkout experience is styled by Stripe
