### ISSUE TITLE
Support for Refunds?

### ISSUE THREAD

**Issue by jimmyjamieson** [sweettooth/ember-cli-stripe#15]
Support for customer refunds would be nice to have. It would help with an admin integration.

**Comment by elithrar** [comment]
Checkout isn't related to Refunds, so this might not make a whole lot of sense. Refunds more heavily rely on the Stripe API and tying into your existing Charge or Customer objects—that kind of logic can't really live in an Ember application as an "add-on".

It might make more sense as a bunch of reusable components that can digest something from a backend API that talks to Stripe.

**Comment by wcurtis** [comment]
Good points @elithrar, I agree the logic doesn't really live client side. @jimmyjamieson the way we do refunds is directly through the [Stripe web app](https://dashboard.stripe.com). If you need tighter admin integration it can be achieved through the Stripe API.

**Comment by jimmyjamieson** [comment]
Hmmm, I might look into my own addon. It would be handy I think for a stripe based ordering system. Time time time :)

**Comment by wcurtis** [comment]
Keep us posted!
