### ISSUE TITLE
Load publishable key from server

### ISSUE THREAD

**Issue by lcpriest** [sweettooth/ember-cli-stripe#16]
I'm using 0.4.0.

Hi! I am currently working on a store-builder, so each store will has their own Stripe account (+ Stripe publishable_key)

It looks that the checkout doesn't render if there isn't anything in the `environment.js`.

Is there a recommended way to dynamically load the key? I noticed you can just put a random string in the environment.js`

```
  ENV.stripe = {
    key: "xxx"
  };
```

And then pass the key directly into the component. Is there a nicer way?

**Comment by b-d-b** [comment]
I had to do something like this for a different plugin, but you can actually do something like this:
```
ENV: {
...
stripe: {
    key: process.env.STRIPE_KEY
}
...
}
```

And in your bash profile or bashrc:

```
export STRIPE_KEY = "my_stripe_key"
```
