### ISSUE TITLE
ReferenceError: StripeCheckout is not defined

### ISSUE THREAD

**Issue by yadomi** [sweettooth/ember-cli-stripe#17]
Hi, 

Sometime when `checkout.js` is not loaded at time or even when it fail to load due to slow connectivity, `StipeCheckout` is not defined on window so [`setupStripe()`](https://github.com/sweettooth/ember-cli-stripe/blob/b466741e1a2bb57634b02a34ff33f844829f9f20/app/components/stripe-checkout.js#L198) fail which is pretty obvious.

Maybe it would make sense to check if `StripeCheckout` exist before trying to do anything ?

**Comment by vladucu** [comment]
hey Felix!
thanks for reporting this....we've run into it too and actually have some improvements coming that will also address this problem

**Comment by vladucu** [comment]
should be fixed with #26

**Comment by NullVoxPopuli** [comment]
I'm getting this error in my test environment. :-\

**Comment by vladucu** [comment]
@NullVoxPopuli what versions of ember-cli and ember-cli-stripe?

**Comment by NullVoxPopuli** [comment]
ember-cli: "^2.12.3",
ember: "~2.13.0",
ember-cli-stripe: "^1.0.1",

my project is open source here: https://gitlab.com/precognition-llc/aeonvera-ui
with a test currently marked to `skip` here: https://gitlab.com/precognition-llc/aeonvera-ui/blob/master/tests/acceptance/registration/event/editing/goes-back-to-add-stuff-test.ts#L58

**Comment by yohanmishkin** [comment]
Not sure if it's helpful, but I'm actually experiencing the same issue in an acceptances test after all assertions pass.

Versions:
```
ember-cli: 2.14.2
ember-cli-stripe: 1.0.1
```

**Comment by mminkoff** [comment]
I see it in tests and production.

ember: 2.14.1
ember-cli-stripe: 1.0.1
